logger:
  level: debug  

scp:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
        advertise : o5gs-scp  # Docker 네트워크상의 SCP 주소
    client:
      nrf:
        - uri: http://o5gs-nrf:7777
